{% set name = "rbcl" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.python.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a0bf43234a2987b67b451d1e61efe5666c12a236001e8ace788307ce5f2ad698

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - setuptools
    - pystache 0.6.5
    - pip
    - wheel
    - libsodium 1.0.18
  run:
    - python
    - barriers

test:
  imports:
    - rbcl
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/nthparty/rbcl
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Python library that bundles libsodium and provides wrappers for its Ristretto group functions.
  description: Python library that bundles libsodium and provides wrappers for its Ristretto group functions.
  doc_url: https://github.com/nthparty/rbcl
  dev_url: https://github.com/nthparty/rbcl

extra:
  recipe-maintainers:
    - boldorider4
