{% set name = "rbcl" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: file:///Users/jolivieri/repos/aggregate/rbcl-feedstock/rbcl-1.0.1.tar.gz
  sha256: a0bf43234a2987b67b451d1e61efe5666c12a236001e8ace788307ce5f2ad698

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - setuptools 67.8.0  # because upstream requires ~=67.6
    - pystache 0.6.5
    - pip
  run:
    - python

test:
  imports:
    - rbcl
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python library that bundles libsodium and provides wrappers for its Ristretto group functions.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - boldorider4
